# ------------------------------------------------------------------ #
#                                                                    #
#           SymPy CI script for Github Actions                       #
#                                                                    #
#   Runs each time a pull request is opened, pushed or merged        #
#                                                                    #
# ------------------------------------------------------------------ #

name: test
on: [pull_request]
jobs:
  # -------- Run benchmarks against master and previous release ---- #

  benchmarks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          # Checkout repo with full history
          fetch-depth: 0
      - run: pip install asv virtualenv packaging
      - run: git submodule add https://github.com/sympy/sympy_benchmarks.git

        # Need to make sure we can access the branches from the main repo. We
        # will run benchmarks for the PR, for master and for the previous
        # release. The version branch names below should be updated once there
        # has been a newer release of sympy. The list of branches to check is
        # also specified in asv.conf.actions.json which should be updated as
        # well.

      - run: git remote add upstream https://github.com/sympy/sympy.git
      - run: git fetch upstream master
      - run: git fetch upstream 1.14

      - name: Configure benchmarks
        run: asv machine --yes --config asv.conf.actions.json

        # This is the slow part:
      - name: Run benchmarks
        run: asv run --config asv.conf.actions.json

        # Output benchmark results
      - run: asv compare upstream/master HEAD --config asv.conf.actions.json --factor 1.5 | tee pr_vs_master.txt
      - run: asv compare upstream/master HEAD --config asv.conf.actions.json --factor 1.5 --only-changed | tee pr_vs_master_changed.txt
      - run: asv compare upstream/1.14 upstream/master --config asv.conf.actions.json --factor 1.5 | tee master_vs_release.txt
      - run: asv compare upstream/1.14 upstream/master --config asv.conf.actions.json --factor 1.5 --only-changed | tee master_vs_release_changed.txt

        # we save all outputs as artifacts that can be downloaded from the
        # GitHub Actions summary page.

      - name: Upload results as artifacts
        uses: actions/upload-artifact@v6
        with:
          name: benchmarks
          path: |
            pr_vs_master.txt
            pr_vs_master_changed.txt
            master_vs_release.txt
            master_vs_release_changed.txt